### PR TITLE
Set timezone and allow to build version set on environment

### PR DESCRIPTION
**Pull request by davidmpaz**
Hi,

thanks for this Repo, i just made some small changes and wanted to put them under your consideration

Thanks again.

Regards,
David

### CODE REVIEW

**Comment by justb4** [comment]
@davidmpaz looks good, only one question, no time to test: is setting `TZ` with `ENV` working? I know this works on Ubuntu, but Alpine may have different behaviour.

**Comment by justb4** [comment]
AnD you may want to update the README, "Build Options": refers to 5.3 (maybe leave version out), plus the new env var options.

**Comment by davidmpaz** [comment]
Hi @justb4,

> is setting TZ with ENV working? 

it did.

give it a try on your end whenever you have time, just to be sure. I have updated docs and did make the variables used for timezone to match that one in README.

cheers

**Comment by davidmpaz** [comment]
By the way, any idea on how to run the image on docker-compose?

I have tried with no success. Thanks!

**Review by justb4 — APPROVED** [review]
LGTM

**Pull request merged**
