### PR TITLE
Supporting custom plugins

### PR DESCRIPTION
**Pull request by andrelramos**
This PR add support to custom JMeter plugins as asked on issue https://github.com/justb4/docker-jmeter/issues/33.

### CODE REVIEW

**Comment by justb4** [comment]
Have little time to test this. Is this working for you? Only .jar files needed for plugins? Then I can merge.

**Comment by andrelramos** [comment]
@justb4 This is working for me. I'm using it on my company CI/CD pipelines.

Only the .jar files is necessary on the plugins volume.

**Comment by justb4** [comment]
Thanks @andrelramos !

**Review by justb4 — COMMENTED** [review]
ok!

**Pull request merged**
